name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # Checkout code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Setup Node
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24

    # Install dependencies
    - name: Install Dependencies
      run: npm install

    # Run tests
    - name: Skip Tests
      run: echo "No tests configured"

    # Deploy to Vercel
    - name: Trigger Vercel Deploy
      run: |
        curl -X POST ${{ secrets.VERCEL_LOCKFORGE_HOOK }}

    # Deploy to Render
    # - name: Trigger Render Deploy
    #   run: |
    #     curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}